### ISSUE TITLE
框架的官方API可以弹出更新框，自己码云模拟一样的json格式数据就没法弹出，为什么呢？求解惑

### ISSUE THREAD

**Issue by YIRUIJIE** [xuexiangjys/XUpdate#124]
**问题描述（必填）**
```java
//默认App更新 + 自定义Api + 自定义提示弹窗(系统）
private String mUpdateUrl3 = "https://gitee.com/xuexiangjys/XUpdate/raw/master/jsonapi/update_custom.json"; //框架的API
private String mUpdateUrl6 = "https://yiruijie.gitee.io/json1";  //自己前端搞的API，通过码云的`Gitee Pages`发布
```
这是我自己搞的后台API服务源码：[https://gitee.com/yiruijie/json1](https://gitee.com/yiruijie/json1)，json格式和框架页面展示的完全一致，**使用框架的API很好用，可以弹出更新、下载APP等都没有问题**，但是使用我自己的总是出现“网络请求错误403”，无法弹窗提示更新的情况，如下图所示：
![image](https://user-images.githubusercontent.com/46518653/111095300-159b4880-8578-11eb-9525-8048d263ca52.png)
您写的一些文档我看过几遍了，我一直还是结局不了这个问题，希望您可以帮我看看，找找原因！

**使用的XUpdate版本（必填）**
'com.github.xuexiangjys:XUpdate:2.0.7'  // androidx版本

**如何重现（必填）**
重现的步骤:
我直接使用的框架中的源码，并没有改其它的，我搞的后台API更新服务也是和官方一样的json格式，就是没使用官方的后台源码搭建，就是无法弹出更新提示。下面是代码：
```java
public class LoginActivity extends Activity {
    //默认App更新 + 自定义Api + 自定义提示弹窗(系统）
    private String mUpdateUrl3 = "https://gitee.com/xuexiangjys/XUpdate/raw/master/jsonapi/update_custom.json";
    private String mUpdateUrl6 = "https://yiruijie.gitee.io/json1";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
//默认App更新 + 自定义Api + 自定义提示弹窗(系统）
        XUpdate.newBuild(this)
//                .updateUrl(mUpdateUrl3)
                .updateUrl(mUpdateUrl6)
                .updateChecker(new DefaultUpdateChecker() {
                    @Override
                    public void onBeforeCheck() {
                        super.onBeforeCheck();
                        CProgressDialogUtils.showProgressDialog(LoginActivity.this, "查询中...");
                    }

                    @Override
                    public void onAfterCheck() {
                        super.onAfterCheck();
                        CProgressDialogUtils.cancelProgressDialog(LoginActivity.this);
                    }

                    @Override
                    public void noNewVersion(Throwable throwable) {
                        super.noNewVersion(throwable);
                        // 没有最新版本的处理
                    }
                })
                .updateParser(new CustomUpdateParser())
                .updatePrompter(new CustomUpdatePrompter())
                .update();
       }
}
```

**期望的效果**
可以使用自己搞的后台API更新服务，让软件弹出提示更新的弹窗，我需要怎么做？
如果是我后台的json格式有误，我需要怎么改？

**日志**
```java
2021-03-15 10:43:46.598 2392-2392/? I/art: Late-enabling -Xcheck:jni
2021-03-15 10:43:46.598 2392-2392/? D/libnativebridge: call UnloadNativeBridge! state=1
2021-03-15 10:43:46.817 2392-2392/? W/System: ClassLoader referenced unknown path: /data/app/com.bysj.yrj-1/lib/x86
2021-03-15 10:43:46.901 2392-2392/com.bysj.yrj D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
2021-03-15 10:43:46.918 2392-2392/com.bysj.yrj D/[XUpdate]: 设置全局是否只在wifi下进行版本更新检查:false
2021-03-15 10:43:46.918 2392-2392/com.bysj.yrj D/[XUpdate]: 设置全局是否使用的是Get请求:true
2021-03-15 10:43:46.918 2392-2392/com.bysj.yrj D/[XUpdate]: 设置全局是否是自动版本更新模式:false
2021-03-15 10:43:46.919 2392-2392/com.bysj.yrj D/[XUpdate]: 设置全局参数, key:versionCode, value:1
2021-03-15 10:43:46.919 2392-2392/com.bysj.yrj D/[XUpdate]: 设置全局参数, key:appKey, value:com.bysj.yrj
2021-03-15 10:43:46.919 2392-2392/com.bysj.yrj D/[XUpdate]: 设置请求超时响应时间:20000ms, 是否使用json:true
2021-03-15 10:43:46.919 2392-2392/com.bysj.yrj D/[XUpdate]: 设置全局更新网络请求服务:com.xuexiang.xupdate.easy.service.OkHttpUpdateHttpServiceImpl
2021-03-15 10:43:46.938 2392-2392/com.bysj.yrj D/[XUpdate]: XUpdate.update()启动:XUpdate{mUpdateUrl='https://yiruijie.gitee.io/json1', mParams={appKey=com.bysj.yrj, versionCode=1}, mApkCacheDir='/storage/emulated/0/Android/data/com.bysj.yrj/cache/xupdate', mIsWifiOnly=false, mIsGet=true, mIsAutoMode=false}
2021-03-15 10:43:46.940 2392-2392/com.bysj.yrj W/System.err: java.lang.Exception: show AlertDialog! title=
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at android.app.AlertDialog.show(AlertDialog.java:134)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at com.bysj.yrj.dao.CProgressDialogUtils.showProgressDialog(CProgressDialogUtils.java:79)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at com.bysj.yrj.dao.CProgressDialogUtils.showProgressDialog(CProgressDialogUtils.java:43)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at com.bysj.yrj.LoginActivity$1.onBeforeCheck(LoginActivity.java:92)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at com.xuexiang.xupdate.UpdateManager.onBeforeCheck(UpdateManager.java:218)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at com.xuexiang.xupdate.UpdateManager.doUpdate(UpdateManager.java:191)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at com.xuexiang.xupdate.UpdateManager.update(UpdateManager.java:183)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at com.xuexiang.xupdate.UpdateManager$Builder.update(UpdateManager.java:800)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at com.bysj.yrj.LoginActivity.onCreate(LoginActivity.java:109)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at android.app.Activity.performCreate(Activity.java:6698)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2623)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2731)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1482)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at android.os.Looper.loop(Looper.java:154)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6145)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
2021-03-15 10:43:46.941 2392-2392/com.bysj.yrj W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
2021-03-15 10:43:46.965 2392-2392/com.bysj.yrj I/HostConnection: HostConnection::HostConnection: pid=2392, tid=2392, this=0xb6965b00
2021-03-15 10:43:46.966 2392-2392/com.bysj.yrj D/HostConnection: HostRPC::connect sucess: app=com.bysj.yrj, pid=2392, tid=2392, this=0xa81b2b00
2021-03-15 10:43:46.966 2392-2392/com.bysj.yrj D/HostConnection: queryAndSetGLESMaxVersion select gles-version: 3.1 hostGLVersion:46 process:com.bysj.yrj
2021-03-15 10:43:46.967 2392-2392/com.bysj.yrj D/HostConnection: recv ProcessPuidReply name=com.bysj.yrj puid=147 g_u64CapsFlag=d
2021-03-15 10:43:46.980 2392-2392/com.bysj.yrj D/[XUpdate]: 开始检查版本信息...
2021-03-15 10:43:47.008 2392-2410/com.bysj.yrj I/art: Do partial code cache collection, code=624B, data=24KB
2021-03-15 10:43:47.008 2392-2410/com.bysj.yrj I/art: After code cache collection, code=624B, data=24KB
2021-03-15 10:43:47.008 2392-2410/com.bysj.yrj I/art: Increasing code cache capacity to 128KB
2021-03-15 10:43:47.050 2392-2410/com.bysj.yrj I/art: Do partial code cache collection, code=624B, data=34KB
2021-03-15 10:43:47.050 2392-2410/com.bysj.yrj I/art: After code cache collection, code=624B, data=34KB
2021-03-15 10:43:47.050 2392-2410/com.bysj.yrj I/art: Increasing code cache capacity to 256KB
2021-03-15 10:43:47.051 2392-2410/com.bysj.yrj I/art: JIT allocated 61KB for compiled code of void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
2021-03-15 10:43:47.051 2392-2410/com.bysj.yrj I/art: Compiler allocated 4MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
2021-03-15 10:43:47.113 2392-2438/com.bysj.yrj I/HostConnection: HostConnection::HostConnection: pid=2392, tid=2438, this=0xb6965b80
2021-03-15 10:43:47.114 2392-2438/com.bysj.yrj D/HostConnection: HostRPC::connect sucess: app=com.bysj.yrj, pid=2392, tid=2438, this=0xa6187280
2021-03-15 10:43:47.114 2392-2438/com.bysj.yrj D/HostConnection: queryAndSetGLESMaxVersion select gles-version: 3.1 hostGLVersion:46 process:com.bysj.yrj
2021-03-15 10:43:47.115 2392-2438/com.bysj.yrj I/OpenGLRenderer: Initialized EGL, version 1.4
2021-03-15 10:43:47.115 2392-2438/com.bysj.yrj D/OpenGLRenderer: Swap behavior 1
2021-03-15 10:43:47.115 2392-2438/com.bysj.yrj I/EGL_adreno: eglCreateContext request GLES major-version=2
2021-03-15 10:43:47.117 2392-2410/com.bysj.yrj I/art: Do full code cache collection, code=65KB, data=54KB
2021-03-15 10:43:47.117 2392-2410/com.bysj.yrj I/art: Starting a blocking GC JitCodeCache
2021-03-15 10:43:47.117 2392-2410/com.bysj.yrj I/art: After code cache collection, code=4KB, data=26KB
2021-03-15 10:43:47.117 2392-2410/com.bysj.yrj I/art: JIT allocated 60KB for compiled code of void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)
2021-03-15 10:43:47.135 2392-2438/com.bysj.yrj D/EGL_adreno: eglCreateContext: 0xb694cbe0: maj 3 min 1 rcv 4
2021-03-15 10:43:47.151 2392-2438/com.bysj.yrj D/EGL_adreno: eglMakeCurrent: 0xb694cbe0: ver 3 1 (tinfo 0xb69b72e0)
2021-03-15 10:43:47.155 2392-2438/com.bysj.yrj D/HostConnection: ExtendedRCEncoderContext GL_VERSION return OpenGL ES 3.1
2021-03-15 10:43:47.156 2392-2438/com.bysj.yrj D/HostConnection: ExtendedRCEncoderContext GL_VERSION return OpenGL ES 3.1
2021-03-15 10:43:47.160 2392-2438/com.bysj.yrj E/EGL_adreno: tid 2438: eglSurfaceAttrib(1327): error 0x3009 (EGL_BAD_MATCH)
2021-03-15 10:43:47.160 2392-2438/com.bysj.yrj W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa7c7b420, error=EGL_BAD_MATCH
2021-03-15 10:43:47.589 2392-2438/com.bysj.yrj E/EGL_adreno: tid 2438: eglSurfaceAttrib(1327): error 0x3009 (EGL_BAD_MATCH)
2021-03-15 10:43:47.589 2392-2438/com.bysj.yrj W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa6182500, error=EGL_BAD_MATCH
2021-03-15 10:43:47.620 2392-2438/com.bysj.yrj D/EGL_adreno: eglMakeCurrent: 0xb694cbe0: ver 3 1 (tinfo 0xb69b72e0)
2021-03-15 10:43:47.854 2392-2438/com.bysj.yrj D/EGL_adreno: eglMakeCurrent: 0xb694cbe0: ver 3 1 (tinfo 0xb69b72e0)
2021-03-15 10:43:48.508 2392-2392/com.bysj.yrj I/Choreographer: Skipped 55 frames!  The application may be doing too much work on its main thread.
2021-03-15 10:43:48.510 2392-2438/com.bysj.yrj D/EGL_adreno: eglMakeCurrent: 0xb694cbe0: ver 3 1 (tinfo 0xb69b72e0)
2021-03-15 10:43:48.512 2392-2438/com.bysj.yrj D/EGL_adreno: eglMakeCurrent: 0xb694cbe0: ver 3 1 (tinfo 0xb69b72e0)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err: java.lang.Exception: Toast callstack! strTip=
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at android.widget.Toast.show(Toast.java:130)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at com.xuexiang.xutil.tip.ToastUtils.showToast(ToastUtils.java:98)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at com.xuexiang.xutil.tip.ToastUtils.toast(ToastUtils.java:48)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at com.xuexiang.xutil.tip.ToastUtils.toast(ToastUtils.java:74)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at com.bysj.yrj.dao.MyApp$1.onFailure(MyApp.java:56)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at com.xuexiang.xupdate._XUpdate.onUpdateError(_XUpdate.java:224)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at com.xuexiang.xupdate._XUpdate.onUpdateError(_XUpdate.java:212)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker.onCheckError(DefaultUpdateChecker.java:116)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker.access$100(DefaultUpdateChecker.java:46)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker$1.onError(DefaultUpdateChecker.java:70)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at com.xuexiang.xupdate.easy.service.OkHttpUpdateHttpServiceImpl$1.onError(OkHttpUpdateHttpServiceImpl.java:101)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at com.zhy.http.okhttp.OkHttpUtils$2.run(OkHttpUtils.java:172)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at android.os.Looper.loop(Looper.java:154)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6145)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
2021-03-15 10:43:48.521 2392-2392/com.bysj.yrj W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
2021-03-15 10:43:48.568 2392-2438/com.bysj.yrj E/EGL_adreno: tid 2438: eglSurfaceAttrib(1327): error 0x3009 (EGL_BAD_MATCH)
2021-03-15 10:43:48.568 2392-2438/com.bysj.yrj W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa7db3d60, error=EGL_BAD_MATCH
2021-03-15 10:43:48.587 2392-2438/com.bysj.yrj D/EGL_adreno: eglMakeCurrent: 0xb694cbe0: ver 3 1 (tinfo 0xb69b72e0)
2021-03-15 10:43:49.042 2392-2438/com.bysj.yrj D/EGL_adreno: eglMakeCurrent: 0xb694cbe0: ver 3 1 (tinfo 0xb69b72e0)
```

**设备信息**
全机型

**附加信息**
框架的源程序代码直接可以使用，可以弹出更新弹窗，但是我自定义的和框架API一样的JSON格式就是不行的，很迷惑。

**Comment by xuexiangjys** [comment]
403错误你跑这里来问？先自己百度百度403错误是什么吧.......

**Comment by YIRUIJIE** [comment]
> 403错误你跑这里来问？先自己百度百度403错误是什么吧.......

我只是改了一个更新的访问链接，我网页访问json也没问题，就出现这个了！
还有就是，这个框架我应该可以不使用你给的springboot的框架搭建吧！我自己可以搭建格式一样的json链接使用吗？

**Comment by xuexiangjys** [comment]
接口服务可不是你这样写的...网页和移动端不一样,ok?

**Comment by YIRUIJIE** [comment]
感谢解惑，差不多明白了，还是要想办法用springboot搭一个吧！又是一个挑战，哈哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月15日(周一) 晚上9:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xuexiangjys/XUpdate] 框架的官方API可以弹出更新框，自己码云模拟一样的json格式数据就没法弹出，为什么呢？求解惑 (#124)




 
接口服务可不是你这样写的...网页和移动端不一样,ok?
