### ISSUE TITLE
程序正在进行版本更新!错误 正在回收资源

### ISSUE THREAD

**Issue by LGlxb** [xuexiangjys/XUpdate#144]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUpdate/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUpdate/wiki)，并且确保是框架的问题。
3.参考[常见问题](https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

----

**问题描述（必填）**
正在集成版本更新功能 log日志正在进行版本更新-> 正在回收资源
2021-12-02 15:36:55.353 396-396/com.lskj.eworker W/System.err:     at com.xuexiang.xupdate._XUpdate.onUpdateError(_XUpdate.java:311)
2021-12-02 15:36:55.353 396-396/com.lskj.eworker W/System.err:     at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker.checkVersion(DefaultUpdateChecker.java:57)
2021-12-02 15:36:55.353 396-396/com.lskj.eworker W/System.err:     at com.xuexiang.xupdate.UpdateManager.checkVersion(UpdateManager.java:244)
2021-12-02 15:36:55.353 396-396/com.lskj.eworker W/System.err:     at com.xuexiang.xupdate.UpdateManager.doUpdate(UpdateManager.java:212)
2021-12-02 15:36:55.353 396-396/com.lskj.eworker W/System.err:     at com.xuexiang.xupdate.UpdateManager.update(UpdateManager.java:193)
2021-12-02 15:36:55.353 396-396/com.lskj.eworker W/System.err:     at com.xuexiang.xupdate.UpdateManager$Builder.update(UpdateManager.java:849)
**使用的XUpdate版本（必填）**
2.1.1

**如何重现（必填）**
重现的步骤:
进入界面检查版本更新

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
![c1e40cf4d82d9182b99fcff53606509](https://user-images.githubusercontent.com/44798106/144378936-1b7be391-cb98-44ef-86b1-affbe966610b.png)
![50beab1ce9719f928887118a07cc7df](https://user-images.githubusercontent.com/44798106/144378952-166a9d30-997a-47ed-bd03-76860d5fb518.png)

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为P20]
 - Android版本: [e.g. Android 7.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by xuexiangjys** [comment]
更新方法的调用地方呢?
