### ISSUE TITLE
集成后从后台收集用户报错信息，不只是否是xupdate的原因

### ISSUE THREAD

**Issue by speedtestcn** [xuexiangjys/XUpdate#146]
集成使用无报错，后台收集报错信息如下：
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.FragmentManagerImpl.n(Unknown Source:11)
	at androidx.fragment.app.FragmentManagerImpl.enqueueAction(Unknown Source:2)
	at androidx.fragment.app.BackStackRecord.a(Unknown Source:69)
	at androidx.fragment.app.BackStackRecord.commit(Unknown Source:1)
	at androidx.fragment.app.DialogFragment.dismissInternal(Unknown Source:87)
	at androidx.fragment.app.DialogFragment.dismiss(Unknown Source:1)
	at com.xuexiang.xupdate.service.DownloadService$b.b(Unknown Source:9)
	at com.xuexiang.xupdate.service.DownloadService$b.a(Unknown Source:6)

**Comment by xuexiangjys** [comment]
你这个用的不是最新的sdk,看上去很久了,建议升级最新sdk
