### ISSUE TITLE
发生android.util.SuperNotCalledException异常

### ISSUE THREAD

**Issue by scloong** [xuexiangjys/XUpdate#154]
**问题描述（必填）**
Thread Name: 'main'
Back traces starts.
android.util.SuperNotCalledException: Activity {com.dcqkj.trueheart/com.xuexiang.xaop.util.PermissionUtils$PermissionActivity} did not call through to super.onCreate()
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2935)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Back traces ends.

**使用的XUpdate版本（必填）**
    implementation 'com.github.xuexiangjys:XUpdate:2.0.7'
    implementation 'com.zhy:okhttputils:2.6.2'
    implementation 'com.github.xuexiangjys.XUtil:xutil-core:2.0.0'
    implementation 'com.github.xuexiangjys.XUtil:xutil-sub:2.0.0'
    implementation 'com.github.xuexiangjys.XAOP:xaop-runtime:1.1.0' 

**设备信息**
 - 设备名: [Redmi Note 3]
 - Android版本: [Android 9]

**Comment by xuexiangjys** [comment]
你这和XUpdate有什么关系？
