### ISSUE TITLE
java.lang.RuntimeException: Unable to get provider com.xuexiang.xupdate.utils.UpdateFileProvider

### ISSUE THREAD

**Issue by FeiouWang** [xuexiangjys/XUpdate#156]
**提Bug前需要做的事情**

1.如果是集成问题的话，请保证仔细按照[如何引用](https://github.com/xuexiangjys/XUpdate/wiki/%E5%A6%82%E4%BD%95%E5%BC%95%E7%94%A8)的步骤，一步一步来，不要跳步骤！
2.详细阅读过[使用手册](https://github.com/xuexiangjys/XUpdate/wiki)，并且确保是框架的问题。
3.参考[常见问题](https://github.com/xuexiangjys/XUpdate/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98),可以解决你出现的绝大多数问题!

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

----

**问题描述（必填）**
在Android10版本进行调试没有问题，但是需要在Android4.4的设备上进行适配，进行调试安装时提示错误

E/AndroidRuntime: *** FATAL EXCEPTION TIME : 3404.4014
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yy.sgs.car.activity, PID: 10136
    java.lang.RuntimeException: Unable to get provider com.xuexiang.xupdate.utils.UpdateFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.xuexiang.xupdate.utils.UpdateFileProvider" on path: DexPathList[[zip file "/data/app/com.yy.sgs.car.activity-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.yy.sgs.car.activity-1, /vendor/lib, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:4793)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
        at android.app.ActivityThread.access$1500(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xuexiang.xupdate.utils.UpdateFileProvider" on path: DexPathList[[zip file "/data/app/com.yy.sgs.car.activity-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.yy.sgs.car.activity-1, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4778)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:816) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:632) 
        at dalvik.system.NativeStart.main(Native Method) 

**使用的XUpdate版本（必填）**
com.github.xuexiangjys:XUpdate:2.1.3

**如何重现（必填）**
进行调试安装

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: 定制型号
 - Android版本: 4.4
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
![image](https://user-images.githubusercontent.com/73068485/180103585-4a4b7695-f75f-433d-a938-bf1e6bb27ec3.png)

**Comment by kangear** [comment]
6.0.1 遇到同样的问题
