### ISSUE TITLE
UncaughtException detected: java.lang.NullPointerException: [UpdateManager.Builder] : updateHttpService == null

### ISSUE THREAD

**Issue by Lyl521** [xuexiangjys/XUpdate#29]
UncaughtException detected: java.lang.NullPointerException: [UpdateManager.Builder] : updateHttpService == null
        at com.xuexiang.xupdate.utils.UpdateUtils.requireNonNull(UpdateUtils.java:74)
        at com.xuexiang.xupdate.UpdateManager$Builder.build(UpdateManager.java:643)
        at com.xuexiang.xupdate.UpdateManager$Builder.update(UpdateManager.java:665)

**Comment by xuexiangjys** [comment]
请把使用说明文档看清楚了再用，行否？这里不是给你们提问的地方。
https://github.com/xuexiangjys/XUpdate#2%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8

**Comment by chenzheng8975** [comment]
小米8青春版有时候也是报这个错
