### ISSUE TITLE
自定义版本更新解析器，在代码执行中Gson报错

### ISSUE THREAD

**Issue by BantonSong** [xuexiangjys/XUpdate#30]
具体位置是在（UpdateManager类的findNewVersion方法中，第288行），都是执行UpdateUtils.toJson(updateEntity)方法时报错。

坚果Pro2s（系统8.1），报如下错误：
2019-03-30 00:09:20.538 W/System.err: java.lang.IllegalArgumentException: **class android.content.res.ColorStateList declares multiple JSON fields named mChangingConfigurations**
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:172)
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.Gson.getAdapter(Gson.java:458)
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.Gson.getAdapter(Gson.java:458)
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.Gson.getAdapter(Gson.java:458)
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
2019-03-30 00:09:20.539 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.Gson.getAdapter(Gson.java:458)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.Gson.getAdapter(Gson.java:458)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.Gson.toJson(Gson.java:704)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.Gson.toJson(Gson.java:683)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.Gson.toJson(Gson.java:638)
2019-03-30 00:09:20.540 W/System.err:     at com.google.gson.Gson.toJson(Gson.java:618)
2019-03-30 00:09:20.540 W/System.err:     at com.xuexiang.xupdate.utils.UpdateUtils.toJson(UpdateUtils.java:179)
2019-03-30 00:09:20.540 W/System.err:     at com.xuexiang.xupdate.UpdateManager.findNewVersion(UpdateManager.java:288)
2019-03-30 00:09:20.540 W/System.err:     at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker.processCheckResult(DefaultUpdateChecker.java:132)
2019-03-30 00:09:20.540 W/System.err:     at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker.onCheckSuccess(DefaultUpdateChecker.java:102)
2019-03-30 00:09:20.540 W/System.err:     at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker.access$000(DefaultUpdateChecker.java:46)
2019-03-30 00:09:20.540 W/System.err:     at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker$2.onSuccess(DefaultUpdateChecker.java:77)
2019-03-30 00:09:20.540 W/System.err:     at com.xxx.update.UpdateHttpService$1.onResponse(UpdateHttpService.java:46)
2019-03-30 00:09:20.540 W/System.err:     at com.xxx.update.UpdateHttpService$1.onResponse(UpdateHttpService.java:43)
2019-03-30 00:09:20.540 W/System.err:     at com.xxx.network.rx.RespObserver.onNext(RespObserver.java:156)
2019-03-30 00:09:20.541 W/System.err:     at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:107)
2019-03-30 00:09:20.541 W/System.err:     at io.reactivex.internal.operators.observable.ObservableTakeUntil$TakeUntilMainObserver.onNext(ObservableTakeUntil.java:79)
2019-03-30 00:09:20.541 W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
2019-03-30 00:09:20.541 W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
2019-03-30 00:09:20.541 W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
2019-03-30 00:09:20.541 W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
2019-03-30 00:09:20.541 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2019-03-30 00:09:20.541 W/System.err:     at android.os.Looper.loop(Looper.java:164)
2019-03-30 00:09:20.541 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6906)
2019-03-30 00:09:20.541 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-03-30 00:09:20.541 W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2019-03-30 00:09:20.541 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)

华为Meta20（系统9.0），报如下错误：
2019-03-30 00:22:05.233 W/System.err: **java.lang.IllegalArgumentException: class android.widget.TextView declares multiple JSON fields named mMinWidth**
2019-03-30 00:22:05.233 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:172)
2019-03-30 00:22:05.234 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
2019-03-30 00:22:05.234 W/System.err:     at com.google.gson.Gson.getAdapter(Gson.java:458)
2019-03-30 00:22:05.235 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
2019-03-30 00:22:05.235 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
2019-03-30 00:22:05.235 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
2019-03-30 00:22:05.236 W/System.err:     at com.google.gson.Gson.getAdapter(Gson.java:458)
2019-03-30 00:22:05.236 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117)
2019-03-30 00:22:05.237 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166)
2019-03-30 00:22:05.237 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102)
2019-03-30 00:22:05.237 W/System.err:     at com.google.gson.Gson.getAdapter(Gson.java:458)
2019-03-30 00:22:05.238 W/System.err:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
2019-03-30 00:22:05.238 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
2019-03-30 00:22:05.239 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
2019-03-30 00:22:05.239 W/System.err:     at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
2019-03-30 00:22:05.239 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
2019-03-30 00:22:05.240 W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
2019-03-30 00:22:05.240 W/System.err:     at com.google.gson.Gson.toJson(Gson.java:704)
2019-03-30 00:22:05.241 W/System.err:     at com.google.gson.Gson.toJson(Gson.java:683)
2019-03-30 00:22:05.241 W/System.err:     at com.google.gson.Gson.toJson(Gson.java:638)
2019-03-30 00:22:05.241 W/System.err:     at com.google.gson.Gson.toJson(Gson.java:618)
2019-03-30 00:22:05.242 W/System.err:     at com.xuexiang.xupdate.utils.UpdateUtils.toJson(UpdateUtils.java:179)
2019-03-30 00:22:05.242 W/System.err:     at com.xuexiang.xupdate.UpdateManager.findNewVersion(UpdateManager.java:288)
2019-03-30 00:22:05.243 W/System.err:     at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker.processCheckResult(DefaultUpdateChecker.java:132)
2019-03-30 00:22:05.243 W/System.err:     at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker.onCheckSuccess(DefaultUpdateChecker.java:102)
2019-03-30 00:22:05.243 W/System.err:     at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker.access$000(DefaultUpdateChecker.java:46)
2019-03-30 00:22:05.244 W/System.err:     at com.xuexiang.xupdate.proxy.impl.DefaultUpdateChecker$2.onSuccess(DefaultUpdateChecker.java:77)
2019-03-30 00:22:05.244 W/System.err:     at com.xxx.update.UpdateHttpService$1.onResponse(UpdateHttpService.java:46)
2019-03-30 00:22:05.245 W/System.err:     at com.xxx.update.UpdateHttpService$1.onResponse(UpdateHttpService.java:43)
2019-03-30 00:22:05.245 W/System.err:     at com.xxx.network.rx.RespObserver.onNext(RespObserver.java:156)
2019-03-30 00:22:05.245 W/System.err:     at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:107)
2019-03-30 00:22:05.246 W/System.err:     at io.reactivex.internal.operators.observable.ObservableTakeUntil$TakeUntilMainObserver.onNext(ObservableTakeUntil.java:79)
2019-03-30 00:22:05.246 W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
2019-03-30 00:22:05.247 W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
2019-03-30 00:22:05.247 W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
2019-03-30 00:22:05.247 W/System.err:     at android.os.Handler.handleCallback(Handler.java:891)
2019-03-30 00:22:05.248 W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
2019-03-30 00:22:05.248 W/System.err:     at android.os.Looper.loop(Looper.java:207)
2019-03-30 00:22:05.248 W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7470)
2019-03-30 00:22:05.249 W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-03-30 00:22:05.249 W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
2019-03-30 00:22:05.249 W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by BantonSong** [comment]
网上查到：有可能是序列化的问题

**Comment by xuexiangjys** [comment]
```
java.lang.IllegalArgumentException: class android.widget.TextView 
```
问题在于,你的UpdateEntity字段里怎么会有TextView ？

**Comment by BantonSong** [comment]
没有这个字段，我是参考说明文档上写的：

            return new UpdateEntity()
                    .setHasUpdate(BuildConfig.VERSION_NAME.compareTo(versionName) < 0)
                    .setForce(BuildConfig.VERSION_NAME.compareTo(minVersionName) < 0)
                    .setVersionCode(result.version_code)
                    .setVersionName(versionName)
                    .setUpdateContent(result.release_note)
                    .setDownloadUrl(result.url)
                    .setSize(10000);

size随便写的。都已经解析成功了

**Comment by xuexiangjys** [comment]
你先试试在其他设备上有没有问题，或者打开模拟器试一下原生的系统

**Comment by BantonSong** [comment]
在华为nova1（系统7.0）上也报错，报错信息如下：
 java.lang.IllegalArgumentException: class android.content.res.ColorStateList declares multiple JSON fields named mChangingConfigurations

**Comment by xuexiangjys** [comment]
实在不行就试一下1.0.7版本，我把日志中json序列化去掉了

**Comment by BantonSong** [comment]
没问题了，能弹出升级对话框了，谢谢！
