### ISSUE TITLE
java.lang.VerifyError，请问jar是否有错误？

### ISSUE THREAD

**Issue by WwhOS** [xuexiangjys/XUpdate#43]
com.github.xuexiangjys:XUpdate:1.0.8

java.lang.VerifyError: com/xuexiang/xupdate/utils/UpdateUtils
        at com.xuexiang.xupdate.UpdateManager$Builder.build(UpdateManager.java:642)
        at com.xuexiang.xupdate.UpdateManager$Builder.update(UpdateManager.java:665)

**Comment by xuexiangjys** [comment]
明显是没有问题的，都发了这么多版本下去了

**Comment by WwhOS** [comment]
查到了，gradle配置Gson方式是compileOnly，我的工程中没有使用Gson
compileOnly deps.gson
