### ISSUE TITLE
HUAWEI HRY-AL00Ta 闪退

### ISSUE THREAD

**Issue by zhuiyi1820** [xuexiangjys/XUpdate#58]
**问题描述（必填）**
关屏导致更新闪退

**使用的XUpdate版本（必填）**
compile 'com.qianwen:okhttp-utils:3.8.0'
compile 'com.github.xuexiangjys:XUpdate:1.0.9'

**如何重现（必填）**
重现的步骤:
1. 打开app
2. 更新校验
3. 下载apk
4. 关闭屏幕/锁屏
5.再次打开屏幕应用闪退

**设备信息**
 - 设备名：HUAWEI
 - Android版本：Android 9
 - 设备型号：HRY-AL00Ta
 - 系统版本：EMUI9.0.1

**Comment by xuexiangjys** [comment]
贴一下闪退日志

**Comment by zhuiyi1820** [comment]
java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in base.apk)
	at com.xuexiang.xupdate.service.DownloadService.getNotificationBuilder(DownloadService.java:179)
	at com.xuexiang.xupdate.service.DownloadService.showDownloadCompleteNotification(DownloadService.java:397)
	at com.xuexiang.xupdate.service.DownloadService.access$700(DownloadService.java:54)
	at com.xuexiang.xupdate.service.DownloadService$FileDownloadCallBack.onSuccess(DownloadService.java:352)
	at com.longzx.delivery.ui.function.OKHttpUpdateHttpService$3.onResponse(OKHttpUpdateHttpService.java:106)
	at com.longzx.delivery.ui.function.OKHttpUpdateHttpService$3.onResponse(OKHttpUpdateHttpService.java:93)
	at com.zhy.http.okhttp.OkHttpUtils$5.run(OkHttpUtils.java:256)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

**Comment by xuexiangjys** [comment]
你换一个手机试试呢，你这错误指向的是android源码

**Comment by zhuiyi1820** [comment]
BOSS的手机 😭

**Comment by xuexiangjys** [comment]
把support包提到“”27.1.1“”以上试试
